apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  labels:
    deploymentName: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    deploymentName: {{ .Release.Name }}
  triggers:
{{ toYaml .Values.triggers | indent 3 }}
